# Generated by Django 6.0.6 on 2026-07-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('SME', 'SMEs'), ('Insurance', 'Insurance Company'), ('Commercial', 'Commercial Bank'), ('Microfinance', 'Microfinance Institution')], max_length=50),
        ),
    ]
